name: Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy-preview:
    name: Deploy preview
    runs-on: ubuntu-latest
    environment:
      name: preview
      url: ${{ steps.deploy.outputs.environment_url }}
    env:
      HUGO_ENV: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build site
        run: make build

      - name: Scan infrastructure files for security issues
        run: make tfsec
        continue-on-error: true

      - name: Upload results of security scan
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: tfsec.sarif.json

      - name: Deploy preview site
        if: ${{ env.AWS_ACCESS_KEY_ID != '' && github.event.number != '' }}
        run: make deploy-preview
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
          PREVIEW_ENVIRONMENT: pr-${{ github.event.number }}

      - name: Set environment URL
        if: ${{ env.AWS_ACCESS_KEY_ID != '' && github.event.number != '' }}
        id: deploy
        run: echo "::set-output name=environment_url::https://pr-${{ github.event.number }}.preview.${{ secrets.DOMAIN_NAME }}"
