name: Preview

on:
  pull_request:
    types: [opened, reopened]

jobs:
  deploy-preview:
    name: Create preview deployment
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    env:
      PREVIEW_ENVIRONMENT: pr${{ github.event.number }}
    steps:
      - name: Create deployment
        uses: octokit/request-action@v2.1.0
        with:
          route: POST /repos/{repository}/deployments
          mediaType: |
            previews:
              - ant-man
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
          environment: ${{ env.PREVIEW_ENVIRONMENT }}
          transient_environment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
